# Generated by Django 5.0.2 on 2024-02-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
                ('publish_year', models.IntegerField()),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
